services:
  keycloak-rest-authz-resource-server:
    image: quay.io/keycloak/keycloak:26.1.4
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./rest-authz-resource-server/config/:/opt/keycloak/data/import
    ports:
      - '8180:8080'

  keycloak-bank-rest-authz-resource-server:
    image: quay.io/keycloak/keycloak:26.1.4
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./bank-rest-authz-resource-server/config/:/opt/keycloak/data/import
    ports:
      - '8180:8080'

  keycloak-javascript-adapter:
    image: quay.io/keycloak/keycloak:26.1.4
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-javascript-adapter/config/:/opt/keycloak/data/import
    ports:
      - '8180:8080'